.TH "md__r_e_a_d_m_e" 3 "Thu Jan 15 2015" "Version 9.9" "Version" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- \fBFighterino\fP 
A little Jump'n'Fight game, filled with open source little fighter graphics\&. For a school project\&.
.PP
.SS "\fCHighschool Website\fP"
.PP
.SS "History"
.PP
.SS "Version 0\&.9"
.PP
Reinige die Dateien langsam und Dokumentiere
.PP
Fertige sind:
.PP
\fBchat\&.cpp\fP
.PP
\fBchoosebackground\&.cpp\fP
.PP
\fBchoosemenu\&.cpp\fP
.PP
.SS "Version 0\&.3\&.1"
.PP
Added new Controls, you can see them by typing /controls into the chat and pressing Y for seeing the \fBChat\fP\&.
.PP
Maked KI - Harder for Players\&.
.PP
.SS "Version 0\&.3"
.PP
Added a 4th \fBCharacter\fP called Chenpo\&.
.PP
Added a Icon for the 3rd Arena (Wall Arena)\&.
.PP
Adjusted Sound for Startscreen\&.
.PP
Added Image for Startscreen (+OP+ WINDOWS PAINT +OP+)\&.
.PP
Implement KI for Player against KI\&.
.PP
Implement 2 Player \fBCharacter\fP Menu for 2 \fBCharacter\fP Player Mode\&.
.PP
Added a STUNNED bool for Characters that gets hitted\&.
.PP
Added a temporary Stun picture\&.
.PP
Enemy KI is punching!
.PP
.SS "Version 0\&.2\&.2"
.PP
Added Sounds to the Startscreen, \fBCharacter\fP Menu and Fightscreen\&.
.PP
Adjusted the Screen for the \fBCharacter\fP Menu\&.
.PP
Added indicators for range while Punching\&.
.PP
.SS "Version 0\&.2"
.PP
3 Characters are available now-
.PP
\fBCharacter\fP icons in the fight dialog\&.
.PP
Included an enemy (no interactions right now)\&.
.PP
Added getName nad GetIcon to character class\&.
.PP
Added escape from fight window, so you can go to the Startmenu now\&.
.PP
Added WinningScreen\&.
.PP
Added Lifelosing when punching (This is at the moment global, will be fixed soon)\&.
.PP
.SS "Version 0\&.1\&.5"
.PP
Fixed Jumpingleft of all characters\&.
.PP
Deleted some unnecessary and unused variables\&.
.PP
Added Ahri as \fBCharacter\fP\&.
.PP
.SS "Version 0\&.1\&.4"
.PP
New \fBCharacter\fP Added (1 and 4 can be used now)\&.
.PP
New Icons in the Choosemenu Added\&.
.PP
Added Mirrored animations for the Characters by Jumping, Punching, Crouching, Standing and Walking\&.
.PP
.SS "Version 0\&.1\&.3"
.PP
Bugfix on Windows Version\&.
.PP
Integrated OS indentificator\&.
.PP
The FPS will be changed now when OS is changing\&.
.PP
Implemented mirror images for left and right stand animation\&.
.PP
Did make the first menu button pressable for enter\&.
.PP
.SS "Version 0\&.1\&.1"
.PP
.RS 4
Not fully functional version\&.
.RE
.PP

