.TH "Ui" 3 "Thu Jan 15 2015" "Version 9.9" "Version" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- \fBStartMenu\fP Klasse beschäftigt sich damit das Startfenster anzuzeigen\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBStartMenu\fP Klasse beschäftigt sich damit das Startfenster anzuzeigen\&. 

Erhält Informationen(Mausclicks) vom User welcher Modus ausgewählt wird\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Version from the source code\&.
